### ISSUE TITLE
Build failed when build on MacOS 10.15 

### ISSUE THREAD

**Issue by Zheaoli** [apache/incubator-brpc#970]
**Describe the bug (描述bug)**

When I try to build brpc on MacOS 10.15, the compiler throws multi errors like below:

```bash

In file included from /Users/manjusaka/Documents/project/incubator-brpc/src/butil/strings/sys_string_conversions_mac.mm:11:
/Users/manjusaka/Documents/project/incubator-brpc/src/butil/mac/foundation_util.h:55:48: error: typedef redefinition with different types ('struct OpaqueSecTrustedApplicationRef *' vs 'struct __SecTrustedApplication *')
typedef struct OpaqueSecTrustedApplicationRef* SecTrustedApplicationRef;
                                               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:200:61: note: previous definition is here
typedef struct CF_BRIDGED_TYPE(id) __SecTrustedApplication *SecTrustedApplicationRef API_UNAVAILABLE(ios, watchos, tvos, macCatalyst);
                                                            ^
11 warnings and 2 errors generated.
In file included from /Users/manjusaka/Documents/project/incubator-brpc/src/butil/mac/foundation_util.mm:5:
/Users/manjusaka/Documents/project/incubator-brpc/src/butil/mac/foundation_util.h:54:35: error: typedef redefinition with different types ('struct OpaqueSecTrustRef *' vs 'struct __SecACL *')
typedef struct OpaqueSecTrustRef* SecACLRef;
                                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:216:46: note: previous definition is here
typedef struct CF_BRIDGED_TYPE(id) __SecACL *SecACLRef API_UNAVAILABLE(ios, watchos, tvos, macCatalyst);
                                             ^
In file included from /Users/manjusaka/Documents/project/incubator-brpc/src/butil/mac/foundation_util.mm:5:
/Users/manjusaka/Documents/project/incubator-brpc/src/butil/mac/foundation_util.h:55:48: error: typedef redefinition with different types ('struct OpaqueSecTrustedApplicationRef *' vs 'struct __SecTrustedApplication *')
typedef struct OpaqueSecTrustedApplicationRef* SecTrustedApplicationRef;
                                               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:200:61: note: previous definition is here
typedef struct CF_BRIDGED_TYPE(id) __SecTrustedApplication *SecTrustedApplicationRef API_UNAVAILABLE(ios, watchos, tvos, macCatalyst);
                                                            ^
make[2]: *** [src/CMakeFiles/BUTIL_LIB.dir/butil/mac/bundle_locations.mm.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/manjusaka/Documents/project/incubator-brpc/src/butil/file_util_mac.mm:12:
/Users/manjusaka/Documents/project/incubator-brpc/src/butil/mac/foundation_util.h:54:35: error: typedef redefinition with different types ('struct OpaqueSecTrustRef *' vs 'struct __SecACL *')
typedef struct OpaqueSecTrustRef* SecACLRef;
                                  ^
```

I'm sure I have already fellowed the [getting_started.md](https://github.com/apache/incubator-brpc/blob/master/docs/cn/getting_started.md)

**To Reproduce (复现方法)**

the standard build process like `make bld && cd bld && cmake .. && make -j`

**Expected behavior (期望行为)**

build  success

**Versions (各种版本)**
OS: MacOS 10.15.1
Compiler: `Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`
brpc: the code in master branch
protobuf: protobuf-3.10.0 from homebrew

**Additional context/screenshots (更多上下文/截图)**

**Comment by zyearn** [comment]
Fixed in https://github.com/apache/incubator-brpc/pull/974
